name: 'Build docker'
on:
  push:
    branches-ignore:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
